<?php

/**
 * This is the model class for table "{{expertises}}".
 *
 * The followings are the available columns in table '{{expertises}}':
 * @property string $id
 * @property string $title
 * @property string $description
 * @property string $icon
 * @property string $parent_id
 *
 * The followings are the available model relations:
 * @property Users[] $users
 * @property Expertises $parent
 * @property Expertises[] $childes
 */
class Expertises extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{expertises}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('title', 'required'),
			array('title', 'length', 'max'=>50),
			array('title' ,'compareWithParent') ,
			array('parent_id', 'length', 'max'=>10),
			array('title' ,'filter' ,'filter' => 'strip_tags') ,
			array('description, icon', 'length', 'max'=>255),
			array('parent_id' ,'checkParent') ,
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, title, description, icon, parent_id', 'safe', 'on'=>'search'),
		);
	}

	public function compareWithParent($attribute ,$params)
	{
		if(!empty($this->title) && $this->parent_id){
			$record = Expertises::model()->findByAttributes(array('id' => $this->parent_id ,'title' => $this->title));
			if($record)
				$this->addError($attribute ,'عنوان دسته بندی با عنوان والد یکسان است.');
		}
	}

	public function checkParent($attribute ,$params)
	{
		if(!empty($this->parent_id) && $this->id){
			if($this->parent_id == $this->id)
				$this->addError($attribute ,'دسته بندی نمی تواند زیرمجموعه خودش باشد.');
		}
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'users' => array(self::MANY_MANY, 'Users', '{{doctor_expertises}}(expertise_id, doctor_id)'),
			'parent' => array(self::BELONGS_TO, 'Expertises', 'parent_id'),
			'childes' => array(self::HAS_MANY ,'Expertises' ,'parent_id') ,
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'title' => 'عنوان تخصص',
			'description' => 'توضیح کوتاه',
			'icon' => 'آیکون',
			'parent_id' => 'والد',
			'parent' => 'والد',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('title',$this->title,true);
		$criteria->compare('description',$this->description,true);
		$criteria->compare('icon',$this->icon,true);
		$criteria->compare('parent_id',$this->parent_id,true);
		$criteria->order='id DESC';
		$criteria->addCondition('parent_id IS NOT NULL');

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Expertises the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	public function beforeSave()
	{
		if(empty($this->parent_id))
			$this->parent_id = NULL;
		return parent::beforeSave(); // TODO: Change the autogenerated stub
	}
}
